### ISSUE TITLE
v1.0.0-beta1 Error: Unable to write config. Undefined index: pass 

### ISSUE THREAD

**Issue by AxDSan** [wintercms/web-installer#16]
I get the above error in my installation, everything seems to be working fine, all the steps are properly handled it just breaks when I get to the installation part...

![](https://i.imgur.com/rHCC1p8.jpeg)

**Comment by RomainMazB** [comment]
@AxDSan Is your web-installer up to date?
I've fixed this issue few weeks ago https://github.com/wintercms/web-installer/pull/15

**Comment by mjauvin** [comment]
duplicate of https://github.com/wintercms/web-installer/issues/14

**Comment by bennothommo** [comment]
This fix is still pending for release, which is why it's still present.
